//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumnos
    {
        public Alumnos()
        {
            this.BecasAlumnos = new HashSet<BecasAlumnos>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public bool genero { get; set; }
        public int edad { get; set; }
    
        public virtual ICollection<BecasAlumnos> BecasAlumnos { get; set; }
    }
}
