//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class BecasAlumnos
    {
        public int id { get; set; }
        public Nullable<int> idAlumno { get; set; }
        public Nullable<int> idBecas { get; set; }
        [DisplayName ("Nombre del Alumno")]
        public string NombreAlumno { get; set; }
        [DisplayName("Nombre de la Beca")]
        public string NombreBeca { get; set; }
        [DisplayName("Tipo de la Beca")]
        public string TiopoBeca { get; set; }
        public virtual Alumnos Alumnos { get; set; }
        public virtual Becas Becas { get; set; }
    }
}
